blank_issues_enabled: true
contact_links:
- name: The Rat Zone Discord Server
  url: https://discord.gg/nBXr96K
  about: For help with running the game, or joining the server, join our Discord server.
